language: cpp
compiler: gcc
git:
  depth: 9999999
jobs:
  include:
    - env:
      branches:
        only:
          - nightly
      before_install:
        - if [[ "$TRAVIS_BRANCH" != "nightly" ]]; then exit 0; fi
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN
          CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: atmoswing/atmoswing
            description: Build submitted via Travis CI
          notification_email: pascal.horton@giub.unibe.ch
          build_command_prepend: cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RelWithDebInfo
            -DGDAL_ROOT=$HOME/.libs
          build_command: make -j $(nproc)
          branch_pattern: coverity-scan
cache:
  timeout: 1000
  directories:
    - "$HOME/.libs"
install:
  - chmod +x ci/travis/dependencies-${TARGET}.sh
  - travis_wait 20 timeout 1990 ci/travis/dependencies-${TARGET}.sh || true
script:
  - chmod +x ci/travis/run-${TARGET}.sh
  - travis_wait 25 ci/travis/run-${TARGET}.sh
after_success:
  - if [[ "$DEPLOY" != true ]]; then exit 0; fi
  - chmod +x ci/travis/after-success-${TRAVIS_OS_NAME}.sh
  - ci/travis/after-success-${TRAVIS_OS_NAME}.sh
deploy:
  - provider: gcs
    access_key_id: GOOG2DVQVS5OULIG7WIU4B7F
    secret_access_key:
      secure: QVTqXZ54wsQhUu+QcYQATIuwVe27ZIl+3XnccDL7Q2NUalWulj5p4EyQ5+JmKhUYzdRujCH08ASuQiKtb/vW5q0WnNsElFBixLk2rhUTR7AG7v1Tk20fZkAczha5xtC/jfyr1v5DdqzQJYAUnBsV+9Zr2oNLeSj7YbUuJk9GwLdfdc4DKJ4+AKIZR6n9OqtVYVbMZB89W8l2t/20fO/XOuKBLSiG23K9R9dlv6eawF/9nFPx+EcuSBnkOFBa+Cq0xFKRx/N3LHDhFPtpV5s+hH1Oenbcw2l4KwMwwSaVxCerMnyWW0Hu6Mrcn2P7KlCsOBtt1kKxXHDLmwRZdSUVO+DJKt+/jDAjRncqN++rFnb+B7SbHEBiCfUGuW2xfLPr6W5hKxmuHUC+5LnC0uVwPSpvEzMAAU4Xip7M66U1CxwLHH9/CfnNdTXAorYBbDVBEr5PdpVjgtZoih4oeZjrGsIWW98tfrcfOOiLHQnRb2Bc0oOq1lMguRINg1t67kJKuCFKnIQSzYpkVQ7BkXwl0f460cZ24X3lXVCPatNDvT+SI0QL6LJgiF9psPncQGm9olKyBy6jb1MTEl9NTjKoyWLIbi+JIg66ub0hmzDa4IBJtGWm5MCg4O4v5TpL64qcd5HK5U/odMpXgK5DvjBF3NoejKTRTRmy94dYB5/vGpA=
    bucket: atmoswing-deploy
    skip_cleanup: true
    acl: public-read
    local_dir: deploy
    on:
      repo: atmoswing/atmoswing
      condition: $DEPLOY = true
      branch: nightly
  - provider: gcs
    access_key_id: GOOG2DVQVS5OULIG7WIU4B7F
    secret_access_key:
      secure: QVTqXZ54wsQhUu+QcYQATIuwVe27ZIl+3XnccDL7Q2NUalWulj5p4EyQ5+JmKhUYzdRujCH08ASuQiKtb/vW5q0WnNsElFBixLk2rhUTR7AG7v1Tk20fZkAczha5xtC/jfyr1v5DdqzQJYAUnBsV+9Zr2oNLeSj7YbUuJk9GwLdfdc4DKJ4+AKIZR6n9OqtVYVbMZB89W8l2t/20fO/XOuKBLSiG23K9R9dlv6eawF/9nFPx+EcuSBnkOFBa+Cq0xFKRx/N3LHDhFPtpV5s+hH1Oenbcw2l4KwMwwSaVxCerMnyWW0Hu6Mrcn2P7KlCsOBtt1kKxXHDLmwRZdSUVO+DJKt+/jDAjRncqN++rFnb+B7SbHEBiCfUGuW2xfLPr6W5hKxmuHUC+5LnC0uVwPSpvEzMAAU4Xip7M66U1CxwLHH9/CfnNdTXAorYBbDVBEr5PdpVjgtZoih4oeZjrGsIWW98tfrcfOOiLHQnRb2Bc0oOq1lMguRINg1t67kJKuCFKnIQSzYpkVQ7BkXwl0f460cZ24X3lXVCPatNDvT+SI0QL6LJgiF9psPncQGm9olKyBy6jb1MTEl9NTjKoyWLIbi+JIg66ub0hmzDa4IBJtGWm5MCg4O4v5TpL64qcd5HK5U/odMpXgK5DvjBF3NoejKTRTRmy94dYB5/vGpA=
    bucket: atmoswing-deploy
    skip_cleanup: true
    acl: public-read
    local_dir: deploy
    on:
      repo: atmoswing/atmoswing
      condition: $DEPLOY = true
      tags: true
