/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asDialogFileSaver__
#define __asDialogFileSaver__

/**
@file
Subclass of asDialogFileSaver, which is generated by wxFormBuilder.
*/

#include "AtmoswingSharedGui.h"
#include <asIncludes.h>

/** Implementing asDialogFileSaver */
class asDialogFileSaver : public asDialogFileSaverVirtual
{
public:
    /** Constructor */
    asDialogFileSaver( wxWindow* parent, const wxString &description );

    wxString GetPath()
    {
        return m_FilePicker->GetPath();
    }

    void SetPath(const wxString &path)
    {
        m_FilePicker->SetPath(path);
    }

};

#endif // __asDialogFileSaver__
