/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asFrameXmlEditor__
#define __asFrameXmlEditor__

/**
@file
Subclass of asFrameXmlEditorVirtual, which is generated by wxFormBuilder.
*/

#include "AtmoswingSharedGui.h"
#include <asIncludes.h>

/** Implementing asFrameXmlEditor */
class asFrameXmlEditor : public asFrameXmlEditorVirtual
{
	public:
		/** Constructor */
		asFrameXmlEditor( wxWindow* parent );
	//// end generated class members

};

#endif // __asFrameXmlEditor__
