/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asFrameAbout__
#define __asFrameAbout__

/**
@file
Subclass of asFrameAbout, which is generated by wxFormBuilder.
*/

#include "AtmoswingSharedGui.h"

//// end generated include

/** Implementing asFrameAbout */
class asFrameAbout : public asFrameAboutVirtual
{
	public:
		/** Constructor */
		asFrameAbout( wxWindow* parent );
	//// end generated class members

    protected:
        wxStaticText* m_VersionWxWidgets;
        wxStaticText* m_VersionEigen;
        wxStaticText* m_VersionTiCPP;
        wxStaticText* m_VersionGdal;
        wxStaticText* m_VersionCurl;
        wxStaticText* m_VersionProj;
        wxStaticText* m_VersionNetCDF;
        wxStaticText* m_VersionVroomGIS;
        wxStaticText* m_VersionWxPlotCtrl;
};

#endif // __asFrameAbout__
