/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asFramePreferences__
#define __asFramePreferences__

/**
@file
Subclass of asFramePreferencesVirtual, which is generated by wxFormBuilder.
*/

#include "AtmoswingSharedGui.h"
#include <asIncludes.h>

/** Implementing asFramePreferencesVirtual */
class asFramePreferences : public asFramePreferencesVirtual
{
public:
    /** Constructor */
    asFramePreferences( wxWindow* parent, wxWindowID id = asWINDOW_PREFERENCES );
    //// end generated class members

protected:
    // Handlers for asFramePreferencesVirtual events.
    void CloseFrame( wxCommandEvent& event );
    void Update();
    void LoadPreferences();
    void SavePreferences();
    void SaveAndClose( wxCommandEvent& event );
    void ApplyChanges( wxCommandEvent& event );
    void OnChangeMultithreadingCheckBox( wxCommandEvent& event );

};

#endif // __asFramePreferences__
