/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asFramePredictandDB__
#define __asFramePredictandDB__

/**
@file
Subclass of asFramePredictandDBVirtual, which is generated by wxFormBuilder.
*/

#include "AtmoswingForecasterGui.h"
#include <asIncludes.h>

/** Implementing asFramePredictandDBVirtual */
class asFramePredictandDB : public asFramePredictandDBVirtual
{
public:
    /** Constructor */
    asFramePredictandDB( wxWindow* parent, wxWindowID id = asWINDOW_PREDICTANDDB );
    //// end generated class members

protected:
    // Handlers for asFramePredictandDBVirtual events.
    void OnSaveDefault( wxCommandEvent& event );
    void CloseFrame( wxCommandEvent& event );
    void OnDataSelection( wxCommandEvent& event );
    void BuildDatabase( wxCommandEvent& event );

};

#endif // __asFramePredictandDB__
