/* Autogenerated by png2wx.pl on Thu Mar 12 16:29:11 2015 */
#ifndef _TOOLBAR_H_
#define _TOOLBAR_H_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP

#include <wx/wx.h>

#endif

#ifdef _MSC_VER
#pragma warning(disable : 4125)  // C4125: decimal digit terminates octal escape sequence
#endif

extern void initialize_img_toolbar_s();

extern void initialize_img_toolbar_m();

extern void initialize_img_toolbar_l();

void cleanup_img_toolbar();

extern wxBitmap* _img_frame_analogs;
extern wxBitmap* _img_frame_distributions;
extern wxBitmap* _img_map_fit;
extern wxBitmap* _img_map_move;
extern wxBitmap* _img_map_select;
extern wxBitmap* _img_map_zoom_in;
extern wxBitmap* _img_map_zoom_out;
extern wxBitmap* _img_open;
extern wxBitmap* _img_preferences;
extern wxBitmap* _img_run;
extern wxBitmap* _img_stop;

#endif /* _TOOLBAR_H_ */
