/* Autogenerated by png2wx.pl on Thu Mar 12 17:15:56 2015 */
#ifndef _TREECTRL_H_
#define _TREECTRL_H_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP

#include <wx/wx.h>

#endif

#ifdef _MSC_VER
#pragma warning(disable : 4125)  // C4125: decimal digit terminates octal escape sequence
#endif

extern void initialize_img_treectrl_s();

extern void initialize_img_treectrl_m();

extern void initialize_img_treectrl_l();

void cleanup_img_treectrl();

extern wxBitmap* _img_icon_lightning;
extern wxBitmap* _img_icon_other;
extern wxBitmap* _img_icon_precip;
extern wxBitmap* _img_icon_temp;
extern wxBitmap* _img_icon_wind;

#endif /* _TREECTRL_H_ */
