/* Autogenerated by png2wx.pl on Fri Mar 11 16:38:06 2011 */
#ifndef _TOOLBAR_H_
#define _TOOLBAR_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images_toolbar(void);

extern wxBitmap img_database_options;
extern wxBitmap img_database_run;
extern wxBitmap img_frame_dots;
extern wxBitmap img_frame_forecaster;
extern wxBitmap img_frame_grid;
extern wxBitmap img_frame_plots;
extern wxBitmap img_frame_viewer;
extern wxBitmap img_map_cross;
extern wxBitmap img_map_cursor;
extern wxBitmap img_map_fit;
extern wxBitmap img_map_move;
extern wxBitmap img_map_zoom_in;
extern wxBitmap img_map_zoom_out;
extern wxBitmap img_open;
extern wxBitmap img_preferences;
extern wxBitmap img_print;
extern wxBitmap img_run_history;
extern wxBitmap img_run;
extern wxBitmap img_run_cancel;

#endif /* _TOOLBAR_H_ */
