/* Autogenerated by png2wx.pl on Thu Mar 17 15:41:17 2011 */
#ifndef _BULLETS_H_
#define _BULLETS_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images_bullets(void);

extern wxBitmap img_arrows_left;
extern wxBitmap img_arrows_right;
extern wxBitmap img_bullet_error;
extern wxBitmap img_bullet_green;
extern wxBitmap img_bullet_white;
extern wxBitmap img_bullet_yellow;
extern wxBitmap img_clock_now;
extern wxBitmap img_close;
extern wxBitmap img_hidden;
extern wxBitmap img_led_green;
extern wxBitmap img_led_off;
extern wxBitmap img_led_red;
extern wxBitmap img_led_yellow;
extern wxBitmap img_plus;
extern wxBitmap img_plus_toggle;
extern wxBitmap img_shown;

#endif /* _BULLETS_H_ */
