/* Autogenerated by png2wx.pl on Thu Mar 12 16:43:20 2015 */
#ifndef _LOGO_H_
#define _LOGO_H_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP

#include <wx/wx.h>

#endif

#ifdef _MSC_VER
#pragma warning(disable : 4125)  // C4125: decimal digit terminates octal escape sequence
#endif

extern void initialize_img_logo();

void cleanup_img_logo();

extern wxBitmap* _img_logo;

#endif /* _LOGO_H_ */
