/* Autogenerated by png2wx.pl on Thu Mar 12 17:12:52 2015 */
#ifndef _MISC_H_
#define _MISC_H_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP

#	include <wx/wx.h>

#endif

#ifdef _MSC_VER
#pragma warning( disable : 4125 ) // C4125: decimal digit terminates octal escape sequence
#endif

extern void initialize_img_misc_s();

extern void initialize_img_misc_m();

extern void initialize_img_misc_l();

void cleanup_img_misc();

extern wxBitmap *_img_bullet_green;
extern wxBitmap *_img_bullet_red;
extern wxBitmap *_img_bullet_white;
extern wxBitmap *_img_bullet_yellow;
extern wxBitmap *_img_close;
extern wxBitmap *_img_hidden;
extern wxBitmap *_img_plus;
extern wxBitmap *_img_shown;
extern wxBitmap *_img_update;

#endif /* _MISC_H_ */
