/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asFrameGridAnalogsValues__
#define __asFrameGridAnalogsValues__

/**
@file
Subclass of asFrameGridAnalogsValues, which is generated by wxFormBuilder.
*/

#include "AtmoswingViewerGui.h"
#include "asIncludes.h"

class asForecastManager;

/** Implementing asFrameGridAnalogsValues */
class asFrameGridAnalogsValues : public asFrameGridAnalogsValuesVirtual
{
public:
    /** Constructor */
    asFrameGridAnalogsValues( wxWindow* parent, int selectedForecast, asForecastManager *forecastManager, wxWindowID id=asWINDOW_GRID_ANALOGS );
    void Init();

protected:
    void OnChoiceForecastChange( wxCommandEvent& event );
    void OnChoiceStationChange( wxCommandEvent& event );
    void OnChoiceDateChange( wxCommandEvent& event );
    virtual void SortGrid( wxGridEvent& event );

private:
    asForecastManager *m_ForecastManager;
    int m_SelectedForecast;
    int m_SelectedStation;
    int m_SelectedDate;
    int m_SortAfterCol;
    Order m_SortOrder;

    bool UpdateGrid();
};

#endif // __asFrameGridAnalogsValues__
