/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asPanelSidebar__
#define __asPanelSidebar__

/**
@file
Subclass of asPanelSidebarVirtual, which is generated by wxFormBuilder.
*/

#include "AtmoswingViewerGui.h"

/** Implementing asPanelSidebar */
class asPanelSidebar : public asPanelSidebarVirtual
{
public:
    /** Constructor */
    asPanelSidebar( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL );

    void ReducePanel();
    bool IsReduced()
    {
        return !m_SizerMain->IsShown(m_SizerContent);
    }

protected:
    // Handlers for asPanelSidebar events.
    void OnReducePanel( wxCommandEvent& event );
    void OnPaint( wxCommandEvent& event );
    wxWindow* GetTopFrame(wxWindow* element);

};

#endif // __asPanelSidebar__
