/** 
 *
 *  This file is part of the AtmoSwing software.
 *
 *  Copyright (c) 2008-2012  University of Lausanne, Pascal Horton (pascal.horton@unil.ch). 
 *  All rights reserved.
 *
 *  THIS CODE, SOFTWARE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY  
 *  OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 */
 
#ifndef __asPanelPlot__
#define __asPanelPlot__

/**
@file
Subclass of asPanelPlot, which is generated by wxFormBuilder.
*/

#include "asIncludes.h"
#include "AtmoswingViewerGui.h"


/** Implementing asPanelPlot */
class asPanelPlot : public asPanelPlotVirtual
{
public:
    /** Constructor */
    asPanelPlot( wxWindow* parent );

    void Print();
    void PrintPreview();
    void ExportSVG();

    wxPlotCtrl* GetPlotCtrl();


protected:
private:
    void OnPlotCtrl(wxPlotCtrlEvent& event);

    DECLARE_EVENT_TABLE()

};


#endif // __asPanelPlot__
