coverage:
  precision: 2
  round: nearest
  range: "20...100"
  status:
    project:
      default:
        target: 40
        threshold: 1
        base: auto
ignore:
  - "/usr/.*"
  - ".*/external/.*"
  - "tests/.*"
  - ".*/tests/.*"
  - "tests/src/*"
  - ".*/tests/src/*"
  - "/home/travis/build/atmoswing/atmoswing/tests/src/*"
  - ".*/libs/.*"
