/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can read the License at http://opensource.org/licenses/CDDL-1.0
 * See the License for the specific language governing permissions
 * and limitations under the License.
 * 
 * When distributing Covered Code, include this CDDL Header Notice in 
 * each file and include the License file (licence.txt). If applicable, 
 * add the following below this CDDL Header, with the fields enclosed
 * by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 * 
 * The Original Software is AtmoSwing. The Initial Developer of the 
 * Original Software is Pascal Horton of the University of Lausanne. 
 * All Rights Reserved.
 * 
 */

/*
 * Portions Copyright 2008-2013 University of Lausanne.
 */
 
#ifndef __asPanelForecast__
#define __asPanelForecast__

/**
@file
Subclass of asPanelForecastVirtual, which is generated by wxFormBuilder.
*/

#include "AtmoswingForecasterGui.h"
#include "img_bullets.h"
#include <wx/awx/led.h>

//// end generated include

class asPanelsManagerForecasts;

/** Implementing asPanelForecast */
class asPanelForecast : public asPanelForecastVirtual
{
public:
    /** Constructor */
    asPanelForecast( wxWindow* parent );

    virtual bool Layout();

    awxLed* GetLed()
    {
        return m_Led;
    }

    void SetPanelsManager(asPanelsManagerForecasts* panelManager)
    {
        m_PanelsManager = panelManager;
    }

    wxString GetParametersFileName()
    {
        return m_TextCtrlParametersFileName->GetValue();
    }

    void SetParametersFileName(const wxString &val)
    {
        m_TextCtrlParametersFileName->SetValue(val);
    }

protected:
    wxWindow* m_ParentFrame;
    awxLed* m_Led;

    void ClosePanel( wxCommandEvent& event );
    void ChangeForecastName( wxCommandEvent& event );



private:
    asPanelsManagerForecasts* m_PanelsManager;
};

#endif // __asPanelForecast__
