name: CMake

on:
  push:
    branches:
    - master
    - feature/
  pull_request:
    branches:
    - master
    - feature/

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: sudo apt-get install libwxbase3.0-dev libnetcdf-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev libtiff5-dev libexpat1-dev libproj-dev libgdal-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/bin

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bin
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/bin
      run: cmake --build . --config ${{env.BUILD_TYPE}}
      
    - name: Copy test files
      working-directory: ${{github.workspace}}
      run: cp -R tests/files/ bin/tests

    - name: List directory content
      working-directory: ${{github.workspace}}/bin
      run: tree .

    - name: Test
      working-directory: ${{github.workspace}}/bin
      run: tests/atmoswing-tests
