name: CMake

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
    - feature/*

env:
  BUILD_TYPE: Release

jobs:
  build-and-test-server-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: sudo apt-get install libwxbase3.0-dev libnetcdf-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev libproj-dev libeccodes-dev

    - name: Build Jasper lib
      run: chmod +x ci/github/build-jasper.sh && ci/github/build-jasper.sh

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/bin

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bin
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_OPTIMIZER=1 -DBUILD_FORECASTER=1 -DBUILD_DOWNSCALER=1 -DBUILD_VIEWER=0 -DCREATE_INSTALLER=1 -DUSE_GUI=0

    - name: Build
      working-directory: ${{github.workspace}}/bin
      run: cmake --build . --config ${{env.BUILD_TYPE}} -j$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/bin/tests
      run: ./atmoswing-tests

  build-and-test-desktop-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: sudo apt-get install libwxgtk3.0-gtk3-dev libnetcdf-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev libtiff5-dev libexpat1-dev libproj-dev libgdal-dev libeccodes-dev

      - name: Build Jasper lib
        run: chmod +x ci/github/build-jasper.sh && ci/github/build-jasper.sh

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Configure CMake
        working-directory: ${{github.workspace}}/bin
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_OPTIMIZER=1 -DBUILD_FORECASTER=1 -DBUILD_DOWNSCALER=1 -DBUILD_VIEWER=1 -DCREATE_INSTALLER=1 -DUSE_GUI=1

      - name: Build
        working-directory: ${{github.workspace}}/bin
        run: cmake --build . --config ${{env.BUILD_TYPE}} -j$(nproc)

      - name: Test
        working-directory: ${{github.workspace}}/bin/tests
        run: ./atmoswing-tests

  coverage-scan:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: RelWithDebInfo
      CODECOV_TOKEN: "xxxxxxxxx"

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: sudo apt-get install libwxbase3.0-dev libnetcdf-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev libproj-dev libeccodes-dev lcov

      - name: Build Jasper lib
        run: chmod +x ci/github/build-jasper.sh && ci/github/build-jasper.sh

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Configure CMake
        working-directory: ${{github.workspace}}/bin
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_OPTIMIZER=1 -DBUILD_FORECASTER=1 -DBUILD_DOWNSCALER=1 -DBUILD_VIEWER=0 -DCREATE_INSTALLER=0 -DUSE_GUI=0 -DUSE_CODECOV=1

      - name: Build and run code coverage
        working-directory: ${{github.workspace}}/bin
        run: cmake --build . --config $BUILD_TYPE -j$(nproc) --target atmoswing-coverage

      - name: Display code coverage report
        working-directory: ${{github.workspace}}/bin
        run: lcov --list flhy-coverage.info

      - name: Send to Codecov
        working-directory: ${{github.workspace}}/bin
        run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
