name: Coverity scan

on:
  push:
    branches:
    - code-analysis

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  coverity-scan:
    name: Coverity scan

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: Cache Conan libs
        id: cache-conan
        uses: pat-s/always-upload-cache@v3.0.1
        with:
          path: /home/runner/.conan
          key: ${{runner.os}}-conan

      - name: Setup Conan
        run: |
          pip install conan
          conan profile new default --detect --force
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Get dependencies
        working-directory: ${{github.workspace}}/bin
        run: conan install .. -s build_type=Release -o build_viewer=False -o with_gui=False -o enable_tests=True --build=missing --build=openjpeg

      - name: Configure
        working-directory: ${{github.workspace}}/bin
        run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=1 -DUSE_GUI=0 -DBUILD_VIEWER=0

      - uses: vapier/coverity-scan-action@v1
        with:
          email: ${{secrets.COVERITY_SCAN_EMAIL}}
          token: ${{secrets.COVERITY_SCAN_TOKEN}}
          working-directory: ${{github.workspace}}/bin
          command: make -j $(nproc)
