name: Docker images

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build-forecaster-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Set default docker tag
      if: ${{GITHUB_REF_TYPE}} == 'branch'
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

    - name: Set docker tag based on tag
      if: ${{GITHUB_REF_TYPE}} == 'tag'
      run: echo "DOCKER_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Display Docker tag name
      run: echo "${{DOCKER_TAG}}"

    - name: Build the Docker image
      run: docker build . --file docker/forecaster-server/Dockerfile --tag atmoswing/forecaster:${{DOCKER_TAG}}

    - name: Push the Docker image
      run: docker push atmoswing/forecaster:${{DOCKER_TAG}}

  build-downscaler-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file docker/downscaler-server/Dockerfile --tag atmoswing/downscaler:latest

      - name: Push the Docker image
        run: docker push atmoswing/downscaler:latest

  build-optimizer-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file docker/optimizer-server/Dockerfile --tag atmoswing/optimizer:latest

      - name: Push the Docker image
        run: docker push atmoswing/optimizer:latest
