name: Docker images

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build-forecaster-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: atmoswing/forecaster

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy Dockerfile
      run: cp docker/forecaster/Dockerfile Dockerfile

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


  build-downscaler-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file docker/downscaler/Dockerfile --tag atmoswing/downscaler:latest

      - name: Push the Docker image
        run: docker push atmoswing/downscaler:latest

  build-optimizer-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file docker/optimizer/Dockerfile --tag atmoswing/optimizer:latest

      - name: Push the Docker image
        run: docker push atmoswing/optimizer:latest
