name: Docker Image

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build-forecaster-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file docker/forecaster-server/Dockerfile --tag atmoswing/forecaster:latest

    - name: Push the Docker image
      run: docker push atmoswing/forecaster:latest