name: Docker images

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build-forecaster-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file docker/forecaster-server/Dockerfile --tag atmoswing/forecaster:latest

    - name: Push the Docker image
      run: docker push atmoswing/forecaster:latest

  build-forecaster-image-arm32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file docker/forecaster-server/Dockerfile.arm32v7 --tag atmoswing/forecaster:latest

      - name: Push the Docker image
        run: docker push atmoswing/forecaster:latest

  build-forecaster-image-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file docker/forecaster-server/Dockerfile.arm64v8 --tag atmoswing/forecaster:latest

      - name: Push the Docker image
        run: docker push atmoswing/forecaster:latest

  build-downscaler-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file docker/downscaler-server/Dockerfile --tag atmoswing/downscaler:latest

      - name: Push the Docker image
        run: docker push atmoswing/downscaler:latest

  build-optimizer-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file docker/optimizer-server/Dockerfile --tag atmoswing/optimizer:latest

      - name: Push the Docker image
        run: docker push atmoswing/optimizer:latest
