name: Linux builds

on: push

env:
  BUILD_TYPE: Release

jobs:
  build-server-version:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Conan libs
        id: cache-conan
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: /home/runner/.conan
          key: conan-linux-server

      - name: Setup Conan
        run: |
          pip install conan==1.*
          conan profile new default --detect --force
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Get dependencies
        working-directory: ${{github.workspace}}/bin
        run: conan install .. -s build_type=${{env.BUILD_TYPE}} -o build_viewer=False -o with_gui=False -o enable_tests=True --build=missing --build=openjpeg

      - name: Build
        working-directory: ${{github.workspace}}/bin
        run: conan build ..

      - name: Test
        working-directory: ${{github.workspace}}/bin/bin
        run: ./atmoswing-tests


  build-desktop-version:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install libgtk-3-0 libgtk-3-dev

      - name: Cache Conan libs
        id: cache-conan
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: /home/runner/.conan
          key: conan-linux-desktop

      - name: Setup Conan
        run: |
          pip install conan==1.*
          conan profile new default --detect --force
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Get dependencies
        working-directory: ${{github.workspace}}/bin
        run: conan install .. -s build_type=${{env.BUILD_TYPE}} -o enable_tests=True --build=missing --build=openjpeg -c tools.system.package_manager:mode=install

      - name: Build
        working-directory: ${{github.workspace}}/bin
        run: conan build ..

      - name: Test
        working-directory: ${{github.workspace}}/bin/bin
        run: ./atmoswing-tests
