name: Linux builds

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
    - feature/*

env:
  BUILD_TYPE: Release

jobs:
  build-server-version:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: conan install .. -s build_type=${{env.BUILD_TYPE}} -o build_viewer=False -o with_gui=False -o enable_tests=True --build=missing

    - name: Build
      run: conan build ..

    - name: Test
      working-directory: ${{github.workspace}}/bin/tests
      run: ./atmoswing-tests


  build-desktop-version:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: conan install .. -s build_type=${{env.BUILD_TYPE}} -o build_viewer=True -o with_gui=True -o enable_tests=True --build=missing

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/bin

      - name: Build
        run: conan build ..

      - name: Test
        working-directory: ${{github.workspace}}/bin/tests
        run: ./atmoswing-tests


  coverage-scan:
    runs-on: ubuntu-22.04

    env:
      BUILD_TYPE: RelWithDebInfo

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: conan install .. -s build_type=${{env.BUILD_TYPE}} -o build_viewer=False -o with_gui=False -o enable_tests=True -o code_coverage=True --build=missing

      - name: Build
        run: conan build ..

      - name: Preparing coverage data
        run: lcov --directory . --capture --output-file coverage.info

      - name: Cleaning up coverage data
        run: lcov --remove coverage.info "/usr/*" "*/_deps/*" "*/tests/*" --output-file coverage.info

      - name: Display code coverage report
        run: lcov --list coverage.info

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.info
          fail_ci_if_error: true
          verbose: true
